POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphM0BnbWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNjU3OTk0NTM0fQ.w4Y9v7u02W3abVHmmh4d6rxKcW3ljt3qx8UDvjl6Uws

  {
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2,
    "year": 2022
  }