DELETE http://localhost:3001/api/logout/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphMUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjU4MDc3NjU2fQ.XwmUKkq0z188puCs2aJQH2RXKhdbDo4RImPd7Re5dU0
